### PR TITLE
Add remove export command.

### PR DESCRIPTION
**Pull request by appleboy**
- Add remove export command.
- Add clean command on Makefile.

[Review on Reviewable](https://reviewable.io/reviews/nlf/dlite/100)

### CODE REVIEW

**Comment by nlf** [comment]
can you run `go fmt` for this? your indenting is off

**Comment by appleboy** [comment]
@nlf I already run `gofmt` command. I think `editorconfig` change the indent behavior.

**Comment by nlf** [comment]
ah yeah.. can you remove the editorconfig then? it conflicts with how go is formatted, so we shouldn't be using it.

**Comment by appleboy** [comment]
@nlf I removed `.editorconfig`. Could I ask why it conflicts with how go is formatted? It just update your editor config settings. `Github` will load the config and change display format of files.

**Comment by nlf** [comment]
because `go fmt` formats your code with tabs, and the `.editorconfig` was telling editors to format the code with 2 spaces instead

**Comment by appleboy** [comment]
@nlf You missing some point. I set `golang` files using `tab` with default `2 indent size` not `2 spaces instead`.

https://github.com/appleboy/dlite/commit/31028b635851fb16c136bb58b73740f3efe10426#diff-1e70daafb475c0ce3fef7d2728279182R41

**Pull request merged**
