### PR TITLE
OSX 10.11 rootless mode, move to /usr/local

### PR DESCRIPTION
**Pull request by rrva**
/usr is not writable on OSX 10.11, moving to /usr/local.

### CODE REVIEW

**Comment by rrva** [comment]
Maybe also move /var and /etc to /usr/local/{var,etc} ?

**Comment by nlf** [comment]
this is certainly doable, but root is still needed in order to install the launchd plist, so i'm not really sure what it actually gains us

**Comment by rrva** [comment]
There are several locations which ought to be writable in rootless mode.
Just to clarify: otherwise dlite is not installable since rootless mode is
always on by default in OSX 10.11

```
~/Library/LaunchAgents Per-user agents provided by the user. /Library/
LaunchAgents Per-user agents provided by the administrator. /Library/
LaunchDaemons System-wide daemons provided by the administrator. /System/
Library/LaunchAgents Per-user agents provided by Mac OS X. /System/Library/
LaunchDaemons System-wide daemons provided by Mac OS X.
```

Den 24 aug. 2015 21:01 skrev "Nathan LaFreniere" notifications@github.com:

**Comment by nlf** [comment]
ah, so long as LaunchDaemons is writable then we should be fine. if you wouldn't mind tweaking things so all paths are happy i'll go ahead and merge this.

**Comment by rrva** [comment]
Probably the /Library/LaunchAgents folder is still a writable folder for
the root user in 10.11. /usr is not writable at all, not even for root
Den 24 aug. 2015 22:26 skrev "Ragnar Rova" ragnar.rova@gmail.com:

**Comment by rrva** [comment]
Yeah or /Library/LaunchDaemons whichever fits best
Den 24 aug. 2015 22:29 skrev "Ragnar Rova" ragnar.rova@gmail.com:

**Comment by nlf** [comment]
closed via 18c35a2c56abfa0d4f154cb27293acff89abacbf

**Comment by nlf** [comment]
most files are now stored under a user specified PREFIX which defaults to /usr/local, i think that takes care of this

**Pull request closed without merging**
